# Generated by Django 3.1.4 on 2020-12-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_auto_20201218_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='member_picture',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
