# Generated by Django 3.1.4 on 2020-12-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=20)),
                ('resource_url', models.URLField(null=True)),
                ('resource_file', models.FileField(null=True, upload_to='static/resources/')),
            ],
        ),
    ]
